-- This script is provided by Fubon.

CREATE TABLE ODS_SYSTEM.TWS_PLN_PLAN_JOB_STREAMS_V
(
    SNAP_DATE                  DATE               NOT NULL,
    JOB_STREAM_ID              RAW(16)            NOT NULL,
    WORKSTATION_ID             RAW(16),
    WORKSTATION_NAME           VARCHAR2(16 CHAR)  NOT NULL,
    JOB_STREAM_NAME            VARCHAR2(16 CHAR)  NOT NULL,
    SCHEDULED_TIME             DATE               NOT NULL,
    INTERNAL_IDENTIFIER        CHAR(16 CHAR)      NOT NULL,
  ACTUAL_START               DATE,
  DEADLINE                   DATE,
  EARLIEST_START             DATE,
  LATEST_START               DATE,
  ESTIMATED_DURATION         NUMBER(12)         NOT NULL,
  JOBS_LIMIT                 NUMBER(4)          NOT NULL,
  STATUS                     CHAR(1 CHAR)       NOT NULL,
  INTERNAL_STATUS            CHAR(1 CHAR)       NOT NULL,
  LATE                       CHAR(1 CHAR)       NOT NULL,
  MONITORED                  CHAR(1 CHAR)       NOT NULL,
  ORIGINAL_JOB_STREAM        VARCHAR2(16 CHAR),
  RECORD_NUMBER              NUMBER(12)         NOT NULL,
  ELAPSED_TIME               NUMBER(12)         NOT NULL,
  PRIORITY                   NUMBER(3)          NOT NULL,
  ORIGINAL_PRIORITY          NUMBER(3)          NOT NULL,
  TOTAL_JOBS                 NUMBER(10)         NOT NULL,
  ABEND_JOBS                 NUMBER(10)         NOT NULL,
  EXECUTING_JOBS             NUMBER(10)         NOT NULL,
  FAILED_JOBS                NUMBER(10)         NOT NULL,
  SUCCESSFUL_JOBS            NUMBER(10)         NOT NULL,
  NOT_RUNNING_JOBS           NUMBER(10)         NOT NULL,
  UNDECIDED_JOBS             NUMBER(10)         NOT NULL,
  TOTAL_DEPENDENCIES         NUMBER(5),
  JOB_DEPENDENCIES           NUMBER(5),
  JOB_STREAM_DEPENDENCIES    NUMBER(5),
  INTERNETWORK_DEPENDENCIES  NUMBER(5),
  PROMPT_DEPENDENCIES        NUMBER(5),
  RESOURCE_DEPENDECIES       NUMBER(5),
  FILE_DEPENDENCIES          NUMBER(5),
  UNRESOLVED_DEPENDENCIES    NUMBER(5),
  TIMEZONE                   VARCHAR2(40 CHAR),
  TRANS_SN                   VARCHAR2(20 CHAR),
  EXEC_DATE                  DATE
)