spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jdbc-url: jdbc:oracle:thin:@10.3.0.73:1521:devzxsm
    username: ENC(MUuq6j1C0gJqVZE85gbOJR2fXd2jbnBn)
    password: ENC(KvVLNNJRp0sc26tfUXPhhKOms3H278XO)


  hive-datasource:
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    jdbc-url: jdbc:hive2://10.4.0.25:10000/default;principal=hive/_HOST@KDC.COM;