spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jdbc-url: jdbc:oracle:thin:@172.17.241.246:5211:TSID
    username: ENC(s5IFxjJ3zOoJQXtFnqePwwnfAu5B/3sf)
    password: ENC(cxWqr5ExAvvE4aRwx8pHHOTSBj98Ouko)


  hive-datasource:
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    jdbc-url: jdbc:hive2://tpebnkbdpwh01t:2181,tpebnkbdpwh02t:2181,tpebnkbdpwh03t:2181/default;password=bdpadmin;principal=hive/_HOST@BDP.FBT.COM;serviceDiscoveryMode=zooKeeper;user=bdpadmin;zooKeeperNamespace=hiveserver2;