spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    root: INFO

jasypt:
  encryptor:
    password: Fubon999
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

mail:
  sender:
    email: "kfk.monitor@fubon.com"
  smtp:
    host: "apsmtp.fbt.com"
    port: "25"