spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  level:
    root: INFO

jasypt:
  encryptor:
    password: fubon
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

mail:
  sender:
    email: "noreply@fubon.com"
    passwd: ENC(WEFHaycaZBurnujSJ+nUGAHHXkgwvhKF)
  smtp:
    host: "smtp.gmail.com"
    port: "465"
    auth: "true"
    socketfactory:
      port: "465"
      class: "javax.net.ssl.SSLSocketFactory"